Datos de perfil
SergioRamire/residencia-1 pull request #11
Opened 2022-05-04 23:47 UTC by RouterUIZ007

2022-05-06 02:05 UTC, Natali-Rojas requested changes
No es necesario que elimines los archivos, mejor utiliza este comando que no compartio Fa
**git restore --staged package-lock.json**

**git restore --staged public/css/app.css**

2022-05-06 02:05 UTC, Natali-Rojas commented on app/Http/Livewire/Admin/Datos/Personales.php
> +            'user.curp' => 'required|alpha_num|max:254',
el curp necesita una validación especifica de posiciones para letras y numeros

2022-05-06 02:05 UTC, Natali-Rojas commented on app/Http/Livewire/Admin/Datos/Personales.php
> +            'user.name' => 'required|string|max:254',
En que diferencia como validaste nombre con string de los apellidos con alpha

2022-05-07 18:17 UTC, FaruNL requested changes

2022-05-07 18:17 UTC, Farid-NL commented on resources/views/livewire/admin/datos/confirmation.blade.php
> +        ¿Seguro que desea guardar los cambios <strong>{{ $user->name }} </strong>?
## Descripción

Suena un poco raro que el sistema te llame por tu nombre cuando te pregunta si deseas continuar.

![image](https://user-images.githubusercontent.com/34426099/167264871-0beb74ce-3d60-46ea-8b16-fb602e2bf5c7.png)

## Sugerencia

![image](https://user-images.githubusercontent.com/34426099/167264921-1c5ead38-d0e4-4901-802d-be254984eb80.png)

```suggestion
        ¿Seguro que desea guardar los cambios?
```

2022-05-07 18:17 UTC, Farid-NL commented on resources/views/livewire/admin/datos/personales.blade.php
> +    </x-slot>
## Observación 1

Hace falta cerrar la etiqueta del primer `div` dentro del slot

```suggestion
    <x-slot name="header">

        <div class="max-w-7xl mx-auto pt-5 pb-10 text-center bg-white rounded-lg border shadow-md sm:p-8 dark:bg-gray-800 dark:border-gray-700">
            <div class="flex flex-col items-center">
    
                <img class="mb-3 w-24 h-24 rounded-full shadow-lg" src="{{ Auth::user()->profile_photo_url }} " alt="Bonnie image" />
                <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white" > 
                    {{ auth()->user()->name }}
                    {{ auth()->user()->apellido_paterno }}
                    {{ auth()->user()->apellido_materno }}
                </h5>
                <span class="text-sm text-gray-500 dark:text-gray-400">{{ auth()->user()->email }}</span>
    

            </div>
        </div>
    </x-slot>
```
## Observación 2

Elimina líneas en blanco que podría considerarse innecesarias. Algunas están bien para separar secciones de la vista, sólo se consistente.

```suggestion
    <x-slot name="header">
        <div class="max-w-7xl mx-auto pt-5 pb-10 text-center bg-white rounded-lg border shadow-md sm:p-8 dark:bg-gray-800 dark:border-gray-700">
            
            <div class="flex flex-col items-center">
                <img class="mb-3 w-24 h-24 rounded-full shadow-lg" src="{{ Auth::user()->profile_photo_url }} " alt="Bonnie image"/>
                <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">
                    {{ auth()->user()->name }}
                    {{ auth()->user()->apellido_paterno }}
                    {{ auth()->user()->apellido_materno }}
                </h5>
                <span class="text-sm text-gray-500 dark:text-gray-400">{{ auth()->user()->email }}</span>
            </div>
            
        </div>
    </x-slot>
```

2022-05-07 18:17 UTC, Farid-NL commented on resources/views/livewire/admin/datos/personales.blade.php
> +                    </div>
## Descripción

Podemos mover el botón a la derecha:

![image](https://user-images.githubusercontent.com/34426099/167265726-6b491743-bc9f-4093-8236-e5f6baac2d81.png)

```suggestion
                    <div class="mt-4 flex justify-end">
                        <x-jet-button wire:click="confirmSave()" type="button">
                            Guardar Cambios
                        </x-jet-button>
                    </div>
```

2022-05-07 18:17 UTC, Farid-NL commented on app/Http/Livewire/Admin/Datos/Personales.php
> +            'user.correo_tecnm' => ['required', 'email', 'max:254'],
## Descripción

- Pon los regex correctos para CURP y RFC.
- Además hay que considerar la duplicidad del email y la terminación del `correo_tecnm`.
  - Necesitarás importar `use Illuminate\Validation\Rule;`

```suggestion
            'user.rfc' => ['required', 'regex:/^([A-ZÑ&]{3,4}) ?(?:- ?)?(\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])) ?(?:- ?)?([A-Z\d]{2})([A\d])$/'],
            'user.curp' => ['required', 'regex:/^([A-Z][AEIOUX][A-Z]{2}\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\d])(\d)$/'],
            'user.name' => ['required', 'regex:/^[\pL\pM\s]+$/u', 'max:255'],
            'user.apellido_materno' => ['required', 'regex:/^[\pL\pM\s]+$/u', 'max:255'],
            'user.apellido_paterno' => ['required', 'regex:/^[\pL\pM\s]+$/u', 'max:255'],
            'user.sexo' => ['required', 'regex:/^[F|M]$/u', 'max:1'],
            'user.email' => ['required', 'email', 'max:255', Rule::unique('users', 'email')->ignore($this->user)],
            'user.correo_tecnm' => ['required', 'email', 'ends_with:@oaxaca.tecnm.mx', Rule::unique('users', 'correo_tecnm')->ignore($this->user)],
```

2022-05-07 18:17 UTC, FaruNL commented on app/Http/Livewire/Admin/Datos/Personales.php
> +        ]);
## Descripción

Podrías utilizar un redirección a la misma página actual, de este modo, el usuario no lo hace manual.

**Desventajas:** No se vería bien el mensaje de "datos guardados exitosamente"

```suggestion
        ]);
        return redirect()->route('datos.personales');
```

2022-05-07 20:15 UTC, RouterUIZ007 commented on app/Http/Livewire/Admin/Datos/Personales.php
> +            'user.correo_tecnm' => ['required', 'email', 'max:254'],
eso me faltaba, ya los confirmo

2022-05-07 20:15 UTC, RouterUIZ007 commented on app/Http/Livewire/Admin/Datos/Personales.php
> +        ]);
me parece bien, que recarge la pagina depues

2022-05-07 20:15 UTC, RouterUIZ007 commented on resources/views/livewire/admin/datos/confirmation.blade.php
> +        ¿Seguro que desea guardar los cambios <strong>{{ $user->name }} </strong>?
igual estaba pensando, pero lo habioa dejado paraver que fuera el user que estaba xD, fines practicos pero si esta bien

2022-05-07 20:15 UTC, RouterUIZ007 commented on resources/views/livewire/admin/datos/personales.blade.php
> +    </x-slot>
xD, errores de novato

2022-05-07 20:15 UTC, RouterUIZ007 commented on resources/views/livewire/admin/datos/personales.blade.php
> +                    </div>
Ufff, gracias jejej

2022-05-07 23:10 UTC, FaruNL submitted a review, later dismissed

2022-05-14 23:34 UTC, FaruNL requested changes

2022-05-14 23:34 UTC, FaruNL commented on app/Http/Livewire/Admin/Datos/Personales.php
> +            'area.jefe' => 'required',
```suggestion
            'area.telefono' => ['required', 'numeric', 'digits:10'],
            'area.jefe_area' => ['required', 'regex:/^[\pL\pM\s]+$/u'],
```

2022-05-14 23:34 UTC, FaruNL commented on app/Http/Livewire/Admin/Datos/Personales.php
> +            'user.area_id' => 'required',
```suggestion
            'user.area_id' => ['required',  'exists:areas,id'],
```

2022-05-15 01:44 UTC, RouterUIZ007 commented on app/Http/Livewire/Admin/Datos/Personales.php
> +            'user.area_id' => 'required',
ya quedo compa;ero

2022-05-15 01:45 UTC, RouterUIZ007 commented on app/Http/Livewire/Admin/Datos/Personales.php
> +            'area.jefe' => 'required',
jejee ani los dej asi, por que nada mas leeremos datos, y no se podran editar

2022-05-15 01:45 UTC, RouterUIZ007 commented on app/Http/Livewire/Admin/Datos/Personales.php
> +            'area.jefe' => 'required',
pero ya implemte la suigerencia

2022-06-08 18:10 UTC, closed without merging