Feat: Crud de áreas y de grupos
SergioRamire/residencia-1 pull request #3
Opened 2022-05-04 02:14 UTC by Natali-Rojas

Clases agregadas:

- [ ] Controlador de livewire para la tabla areas
- [ ] Controlador de livewire para la tabla groups

Vistas agregadas:

- [ ] Vista con funcionalidad para CRUD de áreas
- [ ] Vista con funcionalidad  Vista para CRUD de grupos

Clase con código en proceso:
Controlador GradeControllador

Tareas pendientes

-  Vista funcional de inscripciones
-  CRUD de asignación de calificaciones
- Mockups de diseño de entidades intermedias(muchos a muchos)

2022-05-04 04:23 UTC, FaruNL requested changes
Además hay unos archivos que no son necesarios añadirlos en el PR (#5).

2022-05-04 04:23 UTC, FaruNL commented on app/Http/Livewire/Admin/GradeController.php
> +            'grades' => Grade::join('groups', 'grades.group_id', '=', 'groups.id')
`Grade` a que hace referencia?

![image](https://user-images.githubusercontent.com/34426099/166622661-62bdda7c-b93b-425f-b919-025e2981f041.png)

Ya que no existe ningún modelo o controlador con ese nombre:
![image](https://user-images.githubusercontent.com/34426099/166622843-186cc934-405a-4e71-8add-b7a28f40843f.png)

2022-05-04 05:19 UTC, Natali-Rojas commented on app/Http/Livewire/Admin/GradeController.php
> +            'grades' => Grade::join('groups', 'grades.group_id', '=', 'groups.id')
Em la descripción del PR les comenté que está en proceso el el controlador Grade, es decir, subiré más commits que den solución a todo lo que requiere dicho controlador, por lo cuál donde llamo al modelo Grade, estoy editando, y si debe existir el controlador ya sea con el nombre gradeCrontroller u otro identificativo debido a que se necesita esta vista 
![image](https://user-images.githubusercontent.com/36526810/166626559-f1ef3646-b651-45cc-96c0-f18c2b9ce0e5.png)

2022-05-04 05:20 UTC, Natali-Rojas commented on app/Http/Livewire/Admin/GradeController.php
> +            'grades' => Grade::join('groups', 'grades.group_id', '=', 'groups.id')
El PR lo hice para ir subiendo avances de los CRUD que voy dando check y para comentarios de ellos, cuando termine todo lo que me tocó haría el merge

2022-05-04 05:23 UTC, Natali-Rojas commented on app/Http/Livewire/Admin/GradeController.php
> +            'grades' => Grade::join('groups', 'grades.group_id', '=', 'groups.id')
Ya cambie el título del PR para que se entienda mejor

2022-05-04 05:50 UTC, FaruNL requested changes
Todos los archivos relacionados a `Grade`, creo no son necesarios, pues no hay modelo asociado a estos archivos.
Se coló?

---

Revisa los PR #5 y #6 para sugerencias de correcciones.

2022-05-04 06:01 UTC, FaruNL requested changes
Como sugerencia cambia los `{{ __('Palabra') }}` por `Palabra`

---

Revisa los PR #5 y #6 para sugerencias de correcciones.

2022-05-04 06:01 UTC, Farid-NL commented on app/Http/Livewire/Admin/AreaController.php
> +            'telefono' => ['required', 'regex:/^[0-9]+$/'],
### Validación para texto
Laravel provee una validación llamada `alpha` que valida que lo ingresado sea alfabético, incluyendo símbolos especiales. Internamente funciona con la siguiente regex: `/^[\pL\pM]+$/u`.
Esto solventaría el regex de **nombre** y **jefe**, solo faltaría considerar espacios, para esto el regex quedaría así:
`/^[\pL\pM\s]+$/u`

### Validación para números
Laravel provee una validación llamada `numeric`, que solventa esto, además proporciona un mensaje de error más claro:
![image](https://user-images.githubusercontent.com/34426099/166625705-8b03ef50-8834-427b-b2b0-d9d94008b280.png)

### Validación alfanumérica
Laravel provee una validación llamada `alpha_num`, que solventa esto.

## Sugerencia
```suggestion
            'nombre' => ['required', 'regex:/^[\pL\pM\s]+$/u'],
            'jefe' => ['required', 'regex:/^[\pL\pM\s]+$/u'],
            'extension' => ['required', 'numeric'],
            'clave' => ['required', 'alpha_num'],
            'telefono' => ['required', 'numeric'],
```

2022-05-04 06:01 UTC, Farid-NL commented on app/Http/Livewire/Admin/GroupController.php
> +            'nombre' => ['required', 'regex:/^[a-zA-Z\sñáéíóúÁÉÍÓÚ]+$/'],
## Sugerencia
```suggestion
            'capacidad' => ['required', 'numeric'],
            'nombre' => ['required', 'regex:/^[\pL\pM\s]+$/u'],
```

2022-05-04 06:01 UTC, FaruNL commented on resources/views/livewire/admin/areas/confirmation.blade.php
> +            {{ __('Cancelar') }}
Podemos eliminar los las palabras rodeadas de `{{ __() }}`. Ya que esto es usado cuando se desea traducir la palabra.
Como este no es el caso, y la palabra ya está en español pues sólo se queda la palabra

### Sugerencia
```suggestion
            Cancelar
```

2022-05-04 06:01 UTC, FaruNL commented on resources/views/livewire/admin/areas/edit_create.blade.php
> +                    <x-jet-label for="clave" value="{{ __('Clave') }}" />
```suggestion
                    <x-jet-label for="clave" value="Clave" />
```

2022-05-04 06:08 UTC, FaruNL commented on app/Http/Livewire/Admin/GradeController.php
> +            'grades' => Grade::join('groups', 'grades.group_id', '=', 'groups.id')
> En la descripción del PR les comenté que está en proceso el el controlador Grade

No leí bien esa parte, eso lo explica. Oki doki.

2022-05-04 06:12 UTC, Natali-Rojas commented on resources/views/livewire/admin/areas/confirmation.blade.php
> +            {{ __('Cancelar') }}
Vale, ya lo cambio mejor

2022-05-04 06:12 UTC, Natali-Rojas commented on resources/views/livewire/admin/areas/edit_create.blade.php
> +                    <x-jet-label for="clave" value="{{ __('Clave') }}" />
Lo modifico

2022-05-04 06:13 UTC, Natali-Rojas commented on app/Http/Livewire/Admin/GroupController.php
> +            'nombre' => ['required', 'regex:/^[a-zA-Z\sñáéíóúÁÉÍÓÚ]+$/'],
Lo implementaré, subiré un nuevo commit en unos minutos, pero haré pruebas para checar todos los casos con la validación que propones

2022-05-04 14:29 UTC, RouterUIZ007 approved these changes, later dismissed

2022-05-05 15:24 UTC, RouterUIZ007 approved these changes, later dismissed

2022-05-05 16:55 UTC, RouterUIZ007 commented on app/Http/Livewire/Admin/AreaController.php
> +            'telefono' => ['required', 'regex:/^[0-9]+$/'],
https://vee-validate.logaretm.com/v2/guide/rules.html#after

creo que esto puede ayudar, con la aportación de fa 
![image](https://user-images.githubusercontent.com/34783419/166974089-bcbae3ff-bc3b-44c1-8a9a-384e248c73f0.png)

2022-05-06 06:49 UTC, FaruNL approved these changes

2022-05-08 00:50 UTC, FaruNL requested changes

2022-05-08 00:50 UTC, FaruNL commented on resources/views/livewire/admin/areas/index.blade.php
> +    @endif
Creo ya no es necesario este bloque

```suggestion
```

2022-05-08 00:50 UTC, FaruNL commented on resources/views/livewire/admin/areas/index.blade.php
> +                <x-input.icon wire:model="search" class="w-full" type="text" placeholder="Buscar usuarios...">
```suggestion
                <x-input.icon wire:model="search" class="w-full" type="text" placeholder="Buscar departamentos...">
```

2022-05-08 00:50 UTC, FaruNL commented on resources/views/livewire/admin/areas/destroy.blade.php
> +        {{ __('Eliminar Área.') }}
```suggestion
        Eliminar Área
```

2022-05-08 00:50 UTC, FaruNL commented on resources/views/livewire/admin/groups/index.blade.php
> +    @endif
```suggestion
```

2022-05-08 00:50 UTC, FaruNL commented on resources/views/livewire/admin/groups/index.blade.php
> +                <x-input.icon wire:model="search" class="w-full" type="text" placeholder="Buscar usuarios...">
```suggestion
                <x-input.icon wire:model="search" class="w-full" type="text" placeholder="Buscar grupos...">
```

2022-05-15 05:42 UTC, Natali-Rojas commented on resources/views/livewire/admin/areas/index.blade.php
> +    @endif
El mostrar notificaciones de áreas?

2022-06-08 18:23 UTC, closed without merging